### ISSUE TITLE
Upgrading terser to 4.1.3 genrates in webpack build "undefined" error

### ISSUE THREAD

**Issue by ekarlsso** [terser-js/terser#416]
Terser version: 4.1.3
webpack: 4.30.0
terser-webpack-plugin: 1.4.1

The update to terser 4.1.3 causes an undefined error from source code. 4.1.2 works fine.

Rather hard to debug what is causing this issue. Code base is rather large.
Should this issue be more like part of the terser-webpack-plugin?

**Comment by xdumaine** [comment]
We got this error as well. Had a hell of a time tracking down what was causing it and no idea how I'd get a simple reproduce. Pinning back terser fixed it (but pinning terser-webpack-plugin did not)

**Comment by Kagetsume** [comment]
Hit the same thing this morning.   Lost 6 hours debugging it and isolating it to Terser 4.1.3.   Locking terser to to 4.1.2 fixed the problem.

**Comment by tyscorp** [comment]
I have the same issue. Was unable to narrow it down because the bundle is so huge and the error is not useful for debugging.

**Comment by L2jLiga** [comment]
It seems like caused by #363. I'm working on quite big Angular application and Terser works fine for me.

**Comment by L2jLiga** [comment]
PR contains 2 commit. Could you check which one breaks your build?

**Comment by tyscorp** [comment]
@L2jLiga Adding this line back in fixed the issue for me: https://github.com/terser-js/terser/pull/363/commits/3b46b0bbc62edc035102f34d83f90fe6a57884b5#diff-29faf045645d2e76723b44f65c35dbe7L6073

**Comment by tyscorp** [comment]
Adding this line back in fixes the issue for me: https://github.com/terser-js/terser/pull/363/commits/3b46b0bbc62edc035102f34d83f90fe6a57884b5#diff-29faf045645d2e76723b44f65c35dbe7L6073

**Comment by L2jLiga** [comment]
@tyscorp, thank you for investigating

**Comment by L2jLiga** [comment]
I guess this issue is pretty similar to #417. At least #417 was introduced by eb46b0b

**Comment by fabiosantoscode** [comment]
I am finding this really hard to reproduce without any code. 

A good way to reproduce these kinds of issues is with a divide and conquer approach. Can you try modifying your input file such that you're not importing half your project see if that passes, repeat?

Also, what exactly is the error message and stack you can see? Can you enable npmjs.com/source-map-support or use the Terser CLI directly?

At this point I have no idea what this error might be. I've tried stealing tests from uglifyjs to see if one of them crashes but it didn't work.

**Comment by fabiosantoscode** [comment]
I also had a look at the compress code and couldn't find anything which might throw an actual `undefined`.

@evilebottnawi do you know if it is possible that terser-webpack-plugin might throw an undefined in the case of an unknown type of crash? One where a regular error object is thrown, or a string is thrown. I had a look myself but couldn't find any of it.

**Comment by evilebottnawi** [comment]
@fabiosantoscode 
> do you know if it is possible that terser-webpack-plugin might throw an undefined in the case of an unknown type of crash

Should be not, but will be great if somebody provide minimum reproducible test repo with problem

**Comment by ekarlsso** [comment]
> At this point I have no idea what this error might be. I've tried stealing tests from uglifyjs to see if one of them crashes but it didn't work.

I have seen this in one code base but it is pretty big. It is rather big thing to isolate the issue from it. So sorry, can't do it.

**Comment by fabiosantoscode** [comment]
@ekarlsso can you try to do a build without Terser, then run Terser on its result? Or provide the error you're getting? It must be more than the word "undefined".

**Comment by cristian-sima** [comment]
Same here 

![image](https://user-images.githubusercontent.com/12199042/62784101-5db5d780-bac6-11e9-9287-b283c135f8cf.png)

**Comment by evilebottnawi** [comment]
@cristian-sima stop write `Sam here`, it is not help, please provide configuration or minimum reproducible test repo, we don't know you configuration

**Comment by cristian-sima** [comment]
@evilebottnawi here is the configuration
```json
{
  "version": "1.9.0",
  "scripts": {
    "dist": "node script/dist.js & webpack --mode production --progress -p",
    "eslint": "eslint ./client ./script --ext .jsx,.js --ignore-pattern client/styles --fix",
    "flow": "flow check --color=always",
    "start": "node script/dev.js & node server.js",
    "test": "jest",
    "check": "npm-check -u -i babel-jest -i redux-form -i jest --specials=bin,eslint,babel,webpack",
    "test:watch": "jest --watch"
  },
  "repository": {
    "type": "git",
    "url": "****"
  },
  "license": "Apache-2.0",
  "engines": {
    "node": ">= 6.3.1"
  },
  "jest": {
    "transform": {
      "^.+\\.jsx?$": "babel7-jest"
    },
    "setupFiles": [
      "<rootDir>/script/polyfills/tempPolyfills.js"
    ],
    "testRegex": "client/.*-test.js$",
    "modulePaths": [
      "client"
    ]
  },
  "devDependencies": {
    "@babel/plugin-proposal-class-properties": "^7.4.0",
    "@babel/plugin-proposal-export-default-from": "^7.2.0",
    "@babel/plugin-proposal-export-namespace-from": "^7.2.0",
    "@babel/plugin-syntax-dynamic-import": "^7.2.0",
    "@babel/plugin-transform-flow-strip-types": "^7.4.0",
    "@babel/plugin-transform-modules-commonjs": "^7.4.3",
    "@babel/plugin-transform-react-constant-elements": "^7.2.0",
    "@babel/plugin-transform-react-inline-elements": "^7.2.0",
    "@babel/plugin-transform-runtime": "^7.4.3",
    "@babel/preset-env": "^7.4.3",
    "@babel/preset-flow": "^7.0.0",
    "@babel/preset-react": "^7.0.0",
    "@sentry/webpack-plugin": "^1.6.2",
    "babel-core": "^6.26.3",
    "babel-eslint": "10.0.1",
    "babel-jest": "^24.1.0",
    "babel-loader": "^8.0.5",
    "babel-plugin-add-module-exports": "^1.0.0",
    "babel-plugin-flow-react-proptypes": "^25.0.0",
    "babel-plugin-react-html-attrs": "^2.1.0",
    "babel-plugin-react-remove-prop-types": "^3.0.0",
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "babel-plugin-syntax-flow": "^6.18.0",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.5",
    "babel-plugin-transform-flow-strip-types": "^6.22.0",
    "babel-plugin-transform-react-constant-elements": "^6.23.0",
    "babel-plugin-transform-react-inline-elements": "^6.22.0",
    "babel-plugin-transform-react-jsx-source": "^6.22.0",
    "babel-plugin-transform-react-remove-prop-types": "^0.4.24",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "babel7-jest": "^1.0.1",
    "cls": "^0.1.5",
    "css-loader": "^2.1.1",
    "eslint": "5.16.0",
    "eslint-plugin-flowtype": "3.6.1",
    "eslint-plugin-jsx-a11y": "6.2.1",
    "eslint-plugin-react": "7.12.4",
    "file-loader": "^3.0.1",
    "flow-bin": "^0.98.0",
    "flow-status-webpack-plugin": "^0.1.7",
    "jest-cli": "^24.7.1",
    "jest-immutable-matchers": "^2.0.1",
    "json-loader": "^0.5.7",
    "node-sass": "^4.12.0",
    "postcss-loader": "^3.0.0",
    "react-hot-loader": "^4.8.4",
    "redux-devtools-extension": "^2.13.8",
    "redux-mock-store": "^1.5.3",
    "sass-loader": "^7.1.0",
    "style-loader": "^0.23.1",
    "url-loader": "^1.1.2",
    "webpack": "^4.38.0",
    "webpack-bundle-analyzer": "^3.3.2",
    "webpack-cli": "^3.3.0",
    "webpack-dev-server": "^3.3.1",
    "webpack-git-hash": "^1.0.2",
    "webpack-preset": "^0.2.0",
    "webpack-preset-babel": "^0.2.0",
    "webpack-preset-babel-stage-2": "^0.2.0"
  },
  "dependencies": {
    "@sentry/browser": "^5.1.1",
    "@sentry/cli": "github:getsentry/sentry-cli",
    "big.js": "^5.2.2",
    "bootstrap": "^4.3.1",
    "connected-react-router": "^6.4.0",
    "es6-promisify": "^6.0.1",
    "font-awesome": "^4.7.0",
    "history": "^4.9.0",
    "immutable": "^4.0.0-rc.12",
    "lodash.memoize": "^4.1.2",
    "moment": "^2.24.0",
    "npm-check": "^5.9.0",
    "raphael": "^2.2.8",
    "react": "^16.8.6",
    "react-addons-css-transition-group": "^15.6.2",
    "react-addons-shallow-compare": "^15.6.2",
    "react-autosuggest": "^9.4.3",
    "react-datepicker": "^2.5.0",
    "react-dom": "^16.8.6",
    "react-dropzone": "^10.1.4",
    "react-height": "^3.0.0",
    "react-image-gallery": "^0.8.16",
    "react-loadable": "^5.5.0",
    "react-notification-system-redux": "^2.0.0",
    "react-raphael": "^0.9.0",
    "react-redux": "^7.0.3",
    "react-router": "^5.0.0",
    "react-router-dom": "^5.0.0",
    "react-select": "^2.4.3",
    "react-sidebar": "^3.0.2",
    "reactstrap": "^8.0.0",
    "redux": "^4.0.1",
    "redux-form": "8.1.0",
    "redux-paginator-immutable": "^2.6.1",
    "redux-promise-middleware": "^6.1.0",
    "redux-thunk": "^2.3.0",
    "reselect": "^4.0.0",
    "superagent": "^5.0.4",
    "superagent-promise": "^1.1.0",
    "x25": "^2.6.3"
  },
  "author": "*****"
}
```

the `script/dist.js` is this

```js
// @flow
/* eslint-disable no-console, no-undefined */

const fileName = "client/_config/general.json";

const fs = require("fs");

const file = require(`../${fileName}`);

file.isProduction = true;
file.MobilPayURL = "****";
// file.MobilPayURL = "*****";

fs.writeFile(fileName, JSON.stringify(file, null, 2), (err) => {

  if (err) {
    return console.log(err);
  }

  return undefined;
});
```

the command `npm run dist` causes the problem. (**** - means there is private data there)

**Comment by cristian-sima** [comment]
The `webpack.config.js` is

```js
/* global __dirname, module */
/* eslint-disable no-ternary, multiline-ternary, no-console, global-require, no-useless-escape */

const
  pathModule = require("path"),
  webpack = require("webpack"),
  WebpackGitHash = require("webpack-git-hash"),
  fs = require("fs"),
  { version } = require("./package.json");

// const { BundleAnalyzerPlugin } = require("webpack-bundle-analyzer");

const SentryWebpackPlugin = require("@sentry/webpack-plugin");

const
  config = require("./client/_config/general.json"),
  webpackConfig = require("./client/_config/webpack.json");

const entries = [
    {
      name : "extern",
      path : "***",
    },
    {
      name : "settings",
      path : "***",
    },
    {
      name : "partner",
      path : "***",
    },
  ],
  indexFolderPath = "./server/code/";

const
  isDevelopmentMode = !config.isProduction,
  isProductionMode = config.isProduction,
  getDevtool = () => {
    if (isDevelopmentMode) {
      return "cheap-source-map";
    }

    return "hidden-source-map";
  };

const displayInfo = () => {
  if (isDevelopmentMode) {
    return "Running in [development] mode";
  }

  return "Generating production version...";
};

const getEntity = () => {
  const createEntry = (current) => {
    const list = [];

    if (isDevelopmentMode) {
      const {
        devAddress,
        devPort,
      } = webpackConfig;

      list.push(`webpack-dev-server/client?http://${devAddress}:${devPort}`);
      list.push("webpack/hot/only-dev-server");
      list.push("react-hot-loader/patch");
    }

    list.push(`./client/${current}.jsx`);

    return list;
  };

  return entries.reduce((accumulator, { name, path }) => Object.assign(accumulator, {
    [name]: createEntry(path),
  }), {});
};

console.log(displayInfo());

const gitHashPlugin = new WebpackGitHash({
  cleanup  : true,
  callback : (versionHash) => entries.map(({ name }) => {
    const filename = `${indexFolderPath}/${name}.html`;

    return fs.readFile(filename, "utf8", (errRead, data) => {
      if (errRead) {
        return console.log(errRead);
      }

      const
        reg = new RegExp(`src="\/static\/${name}-\\w+.js"`, "u"),
        newData = data.replace(reg, `src="/static/${name}-${versionHash}.js"`);

      return fs.writeFile(filename, newData, (errWrite) => {
        if (errWrite) {
          return console.log(errWrite);
        }

        return null;
      });
    });
  }),
});

module.exports = {
  devtool : getDevtool(),
  entry   : getEntity(),
  mode    : isProductionMode ? "production" : "development",
  output  : {
    path       : pathModule.join(__dirname, "server/static"),
    filename   : "[name]-[githash].js",
    publicPath : "/static/",
  },
  plugins: isProductionMode ? [
    new SentryWebpackPlugin({
      release : version,
      include : [
        ".",
        "./server",
      ],
      ignore: [
        "node_modules",
        // "client",
        "./server/static/help",
        "./server/static/photo",
      ],
      configFile  : ".sentryclirc",
      stripPrefix : ["~/server/"],
    }),
    // new BundleAnalyzerPlugin(),
    new webpack.DefinePlugin({
      "process.env": {
        "NODE_ENV": JSON.stringify("production"),
      },
    }),
    new webpack.DefinePlugin({
      "process.env": {
        "BABEL_ENV": JSON.stringify("production"),
      },
    }),
    new webpack.ContextReplacementPlugin(/moment[\/\\]locale$/u, /ro/u),
    gitHashPlugin,
  ] : [
    // new BundleAnalyzerPlugin(),
    new webpack.DefinePlugin({
      "process.env": {
        "NODE_ENV": JSON.stringify("development"),
      },
    }),
    new webpack.DefinePlugin({
      "process.env": {
        "BABEL_ENV": JSON.stringify("developmentTime"),
      },
    }),
    new webpack.ContextReplacementPlugin(/moment[\/\\]locale$/u, /ro/u),
    new webpack.HotModuleReplacementPlugin(),
    gitHashPlugin,
  ],
  resolve: {
    extensions: [
      ".js",
      ".jsx",
    ],
    modules: [
      "client",
      "node_modules",
    ],
  },
  module: {
    rules: [
      {
        test : /\.jsx?$/u,
        use  : [
          {
            loader: "babel-loader",
          },
        ],
        include: pathModule.join(__dirname, "client"),
      },
      {
        test : /\.scss$/u,
        use  : [
          "style-loader",
          "css-loader",
          "sass-loader",
        ],
      },
      {
        test : /\.css$/u,
        use  : [
          "style-loader",
          "css-loader",
        ],
      },
      {
        test   : /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/u,
        loader : "url-loader?limit=10000&minetype=application/font-woff",
      },
      {
        test   : /\.jpe?g$|\.gif$|\.png$/u,
        loader : "url-loader",
      },
      {
        test   : /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/u,
        loader : "file-loader",
      },
    ],
  },
};
```

**Comment by cristian-sima** [comment]
I've upgraded to node `10.16.2` and the error is still there

I've upgraded all the packages, and is the same error:

```json

{
  "version": "1.9.0",
  "scripts": {
    "dist": "node script/dist.js & webpack --mode production --progress -p",
    "eslint": "eslint ./client ./script --ext .jsx,.js --ignore-pattern client/styles --fix",
    "flow": "flow check --color=always",
    "start": "node script/dev.js & node server.js",
    "test": "jest",
    "check": "npm-check -u -i babel-jest -i jest --specials=bin,eslint,babel,webpack",
    "test:watch": "jest --watch"
  },
  "repository": {
    "type": "git",
    "url": ""
  },
  "license": "Apache-2.0",
  "engines": {
    "node": ">= 10.16.2"
  },
  "jest": {
    "transform": {
      "^.+\\.jsx?$": "babel7-jest"
    },
    "setupFiles": [
      "<rootDir>/script/polyfills/tempPolyfills.js"
    ],
    "testRegex": "client/.*-test.js$",
    "modulePaths": [
      "client"
    ]
  },
  "devDependencies": {
    "@babel/plugin-proposal-class-properties": "^7.5.5",
    "@babel/plugin-proposal-export-default-from": "^7.5.2",
    "@babel/plugin-proposal-export-namespace-from": "^7.5.2",
    "@babel/plugin-syntax-dynamic-import": "^7.2.0",
    "@babel/plugin-transform-flow-strip-types": "^7.4.4",
    "@babel/plugin-transform-modules-commonjs": "^7.5.0",
    "@babel/plugin-transform-react-constant-elements": "^7.5.0",
    "@babel/plugin-transform-react-inline-elements": "^7.2.0",
    "@babel/plugin-transform-runtime": "^7.5.5",
    "@babel/preset-env": "^7.5.5",
    "@babel/preset-flow": "^7.0.0",
    "@babel/preset-react": "^7.0.0",
    "@sentry/webpack-plugin": "^1.8.0",
    "babel-core": "^6.26.3",
    "babel-eslint": "^10.0.2",
    "babel-jest": "^24.1.0",
    "babel-loader": "^8.0.6",
    "babel-plugin-add-module-exports": "^1.0.2",
    "babel-plugin-flow-react-proptypes": "^25.1.0",
    "babel-plugin-react-html-attrs": "^2.1.0",
    "babel-plugin-react-remove-prop-types": "^3.0.0",
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "babel-plugin-syntax-flow": "^6.18.0",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.5",
    "babel-plugin-transform-flow-strip-types": "^6.22.0",
    "babel-plugin-transform-react-constant-elements": "^6.23.0",
    "babel-plugin-transform-react-inline-elements": "^6.22.0",
    "babel-plugin-transform-react-jsx-source": "^6.22.0",
    "babel-plugin-transform-react-remove-prop-types": "^0.4.24",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "babel7-jest": "^1.0.1",
    "cls": "^0.1.5",
    "css-loader": "^3.2.0",
    "eslint": "^6.1.0",
    "eslint-plugin-flowtype": "^4.2.0",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-react": "^7.14.3",
    "file-loader": "^4.2.0",
    "flow-bin": "^0.104.0",
    "flow-status-webpack-plugin": "^0.1.7",
    "jest-cli": "^24.8.0",
    "jest-immutable-matchers": "^2.0.1",
    "json-loader": "^0.5.7",
    "node-sass": "^4.12.0",
    "postcss-loader": "^3.0.0",
    "react-hot-loader": "^4.12.10",
    "redux-devtools-extension": "^2.13.8",
    "redux-mock-store": "^1.5.3",
    "sass-loader": "^7.2.0",
    "style-loader": "^1.0.0",
    "url-loader": "^2.1.0",
    "webpack": "^4.39.1",
    "webpack-bundle-analyzer": "^3.4.1",
    "webpack-cli": "^3.3.6",
    "webpack-dev-server": "^3.8.0",
    "webpack-git-hash": "^1.0.2",
    "webpack-preset": "^0.2.0",
    "webpack-preset-babel": "^0.2.0",
    "webpack-preset-babel-stage-2": "^0.2.0"
  },
  "dependencies": {
    "@sentry/browser": "^5.6.1",
    "@sentry/cli": "github:getsentry/sentry-cli",
    "big.js": "^5.2.2",
    "bootstrap": "^4.3.1",
    "connected-react-router": "^6.5.2",
    "es6-promisify": "^6.0.1",
    "font-awesome": "^4.7.0",
    "history": "^4.9.0",
    "immutable": "^4.0.0-rc.12",
    "lodash.memoize": "^4.1.2",
    "moment": "^2.24.0",
    "npm-check": "^5.9.0",
    "raphael": "^2.2.8",
    "react": "^16.9.0",
    "react-addons-css-transition-group": "^15.6.2",
    "react-addons-shallow-compare": "^15.6.2",
    "react-autosuggest": "^9.4.3",
    "react-datepicker": "^2.8.0",
    "react-dom": "^16.9.0",
    "react-dropzone": "^10.1.7",
    "react-height": "^3.0.0",
    "react-image-gallery": "^0.8.18",
    "react-loadable": "^5.5.0",
    "react-notification-system-redux": "^2.0.0",
    "react-raphael": "^0.9.0",
    "react-redux": "^7.1.0",
    "react-router": "^5.0.1",
    "react-router-dom": "^5.0.1",
    "react-select": "^3.0.4",
    "react-sidebar": "^3.0.2",
    "reactstrap": "^8.0.1",
    "redux": "^4.0.4",
    "redux-form": "^8.2.5",
    "redux-paginator-immutable": "^2.7.0",
    "redux-promise-middleware": "^6.1.1",
    "redux-thunk": "^2.3.0",
    "reselect": "^4.0.0",
    "superagent": "^5.1.0",
    "superagent-promise": "^1.1.0",
    "x25": "^2.7.0"
  },
  "author": ""
}
```

**Comment by fabiosantoscode** [comment]
Could you please try to produce a build without minification and then run terser path/to/bundle.js -mc so we can see a real stack trace?

**Comment by fabiosantoscode** [comment]
I'm pretty sure Terser only throws error objects.

**Comment by cristian-sima** [comment]
@fabiosantoscode I run `webpack --mode development --progress` which generates a lot of files:
![image](https://user-images.githubusercontent.com/12199042/62801440-691cf900-baee-11e9-8a32-e3d10c54469a.png)

![image](https://user-images.githubusercontent.com/12199042/62801489-86ea5e00-baee-11e9-96f2-e7deeb6c4dee.png)


for which file show I run terser?

**Comment by fabiosantoscode** [comment]
Thanks for having a look Cristian. In this case you can use a wildcard, like `path/to/*.js` to match all the chunks.

**Comment by cristian-sima** [comment]
@fabiosantoscode 
![image](https://user-images.githubusercontent.com/12199042/62802719-3e806f80-baf1-11e9-999d-b09de2696a92.png)

**Comment by fabiosantoscode** [comment]
It's probably failing like that because it's trying to minify a payload that's too big. Interesting.

I'm not sure how you accomplish this on windows, but can you minify each file with its own Terser process?

Looks like a command called forfiles can be used.

https://ss64.com/nt/forfiles.html

`FORFILES /p path/to/js/directory /m *.js /c "terser @file -mc"`

But I'm not good at windows at all.

**Comment by tyscorp** [comment]
I ran terser manually on the problem bundle and got the same error as #417 

```
ERROR: Cannot read property '_walk' of null
    at AST_Binary.<anonymous> (<root>/node_modules/terser/lib/ast.js:848:9)
    at mn.node [as _visit] (<root>/node_modules/terser/lib/ast.js:1208:19)
    at AST_Binary._walk (<root>/node_modules/terser/lib/ast.js:845:16)
    at AST_Conditional._walk (<root>/node_modules/terser/lib/ast.js:862:5)
    at mn.node [as _visit] (<root>/node_modules/terser/lib/ast.js:1208:19)
    at AST_Conditional._walk (<root>/node_modules/terser/lib/ast.js:859:21)
    at AST_Dot._walk (<root>/node_modules/terser/lib/ast.js:802:5)
    at mn.node [as _visit] (<root>/node_modules/terser/lib/ast.js:1208:19)
    at AST_Dot._walk (<root>/node_modules/terser/lib/ast.js:800:16)
    at AST_Assign.<anonymous> (<root>/node_modules/terser/lib/ast.js:848:9)
```

**Comment by fabiosantoscode** [comment]
Thanks @tyscorp! Do you still get this error with `inline=false` in the compress options?

**Comment by tyscorp** [comment]
No error if I use `-m -c inline=false` or `-m -c reduce_vars=false`

**Comment by cristian-sima** [comment]
@fabiosantoscode @tyscorp Finally it shows a problem

![image](https://user-images.githubusercontent.com/12199042/62820952-f3a83b80-bb74-11e9-8a41-0837f15cef5b.png)

**Comment by cristian-sima** [comment]
@fabiosantoscode In case I use this `-m -c inline=false` in the command, I got this 

![image](https://user-images.githubusercontent.com/12199042/62820995-b5f7e280-bb75-11e9-8907-48a237643284.png)

**Comment by fabiosantoscode** [comment]
Make sure the argument order is correct :) The order of the arguments of Terser is a bit unintuitive atm and will be changed.

**Comment by cristian-sima** [comment]
@fabiosantoscode stay here. I test it now

**Comment by cristian-sima** [comment]
@fabiosantoscode :( my customer is waiting for new updates on the production and I am stopped by this for more than a week

**Comment by cristian-sima** [comment]
### No errors for using `-m -c inline=false" 

![image](https://user-images.githubusercontent.com/12199042/62821034-8a292c80-bb76-11e9-8c22-53dc3e31dfd6.png)

**Comment by fabiosantoscode** [comment]
Correct, that's a valid workaround.

**Comment by cristian-sima** [comment]
How can I pass it to webpack in production?

**Comment by cristian-sima** [comment]
`webpack --verbose --mode production --progress -p`

**Comment by fabiosantoscode** [comment]
I'm not sure how to configure this in webpack.config.js, I'm never up to date with how that bundler works :)

**Comment by cristian-sima** [comment]
I got it. For those with the same problem it is here `https://webpack.js.org/configuration/optimization/` 

Does the `inline:false` affects in any way my code?

```js
module.exports = {
  optimization: {
    minimizer: [
      new TerserPlugin({
        terserOptions: {
          ecma: undefined,
          warnings: false,
          parse: {},
          compress: {},
          mangle: true, // Note `mangle.properties` is `false` by default.
          module: false,
          output: null,
          toplevel: false,
          nameCache: null,
          ie8: false,
          keep_classnames: undefined,
          keep_fnames: false,
          safari10: false,
        },
      }),
    ],
  },
};
```

**Comment by fabiosantoscode** [comment]
Options that don't have `unsafe_` in them aren't unsafe. You can safely disable individual options and the only thing that happens is a slight increase in code size.

**Comment by cristian-sima** [comment]
@fabiosantoscode Finally it works. Thanks man

**Comment by evilebottnawi** [comment]
@fabiosantoscode so it is bug on terser side, right?

**Comment by fabiosantoscode** [comment]
Correct @evilebottnawi but it would be nice if the webpack plugin propagated the error a bit better. Just `undefined` got everyone including me confused.

**Comment by evilebottnawi** [comment]
@fabiosantoscode good idea, can you create issue with repo/example how we can get error :smile: and will implement it very fast

**Comment by fabiosantoscode** [comment]
@evilebottnawi Gotcha. But you have limited time, as I will be releasing a fix for this soon :)

**Comment by fabiosantoscode** [comment]
Fixed in 1.4.1

**Comment by richarddd** [comment]
I still have this issue, the only option is to set

```javascript
compress: {
       reduce_vars: false,
},
```

Using:
"terser": "^4.1.4"
"terser-webpack-plugin": "^1.4.1",

**Comment by fabiosantoscode** [comment]
@richarddd please try to isolate the bug to a small single file code example and open an issue on terser-js/terser and I'll get to it.

You might have a completely different error, or indeed the very same error

**Comment by richarddd** [comment]
> @richarddd please try to isolate the bug to a small single file code example and open an issue on terser-js/terser and I'll get to it.
> 
> You might have a completely different error, or indeed the very same error

I've nailed it down to this line with mongoose
`mongoose.Types.ObjectId.isValid(value)`

Please see this issue
https://github.com/terser-js/terser/issues/432
